VPATH=../src
CC	 = gcc
CFLAGS	 = -Wall -O3 -march=armv5te -DDEFAULT_DIR='"/share/fozzy/Data/CurrentCost"' -DBASE_URL='"http://fosdick.slyip.net/cgi-bin/"'
LDFLAGS  = -Wall -O3 -march=armv5te
FTDI_LIB = -lftdi -lusb

include ../src/Makefile
