VPATH=../src
CFLAGS	 = -Wall -O3 -DDEFAULT_DIR='"/data/Misc/CurrentCost"' -DBASE_URL='"http://meije/cgi-bin/"'
LDFLAGS  = -Wall -O3
FTDI_INC = -I /usr/include/libftdi1
FTDI_LIB = -lftdi1

include ../src/Makefile
